use crate::{command::AttributeType, gamestate::character::Class};

#[derive(Debug)]
pub struct ClassConfiguration {
    pub weapon_multiplier: f64,
    pub weapon_gem_multiplier: i32,
    pub weapon_attribute_multiplier: i32,
    pub health_multiplier: f64,
    pub item_armor_multiplier: f64,
    pub main_attribute: AttributeType,
    pub item_bonus_multiplier: f64,
    pub armor_multiplier: f64,
    pub max_armor_reduction: f64,
    pub damage_multiplier: f64,
}

impl Class {
    #[must_use]
    pub fn get_config(&self) -> ClassConfiguration {
        match self {
            Class::Warrior => ClassConfiguration {
                health_multiplier: 5.0,
                weapon_multiplier: 2.0,
                item_armor_multiplier: 15.0,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 1.0,
                damage_multiplier: 1.0,
                weapon_gem_multiplier: 1,
                weapon_attribute_multiplier: 1,
                main_attribute: AttributeType::Strength,
                max_armor_reduction: 0.5,
            },
            Class::Mage => ClassConfiguration {
                health_multiplier: 2.0,
                weapon_multiplier: 4.5,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 2,
                item_armor_multiplier: 3.0,
                main_attribute: AttributeType::Intelligence,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 1.0,
                max_armor_reduction: 0.1,
                damage_multiplier: 1.0,
            },
            Class::Scout => ClassConfiguration {
                health_multiplier: 4.0,
                weapon_multiplier: 2.5,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 2,
                item_armor_multiplier: 7.5,
                main_attribute: AttributeType::Dexterity,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 1.0,
                max_armor_reduction: 0.25,
                damage_multiplier: 1.0,
            },
            Class::Assassin => ClassConfiguration {
                health_multiplier: 4.0,
                weapon_multiplier: 2.0,
                weapon_gem_multiplier: 1,
                weapon_attribute_multiplier: 1,
                item_armor_multiplier: 7.5,
                main_attribute: AttributeType::Dexterity,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 1.0,
                max_armor_reduction: 0.25,
                damage_multiplier: 0.625,
            },
            Class::BattleMage => ClassConfiguration {
                health_multiplier: 5.0,
                weapon_multiplier: 2.0,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 1,
                item_armor_multiplier: 3.0,
                main_attribute: AttributeType::Strength,
                item_bonus_multiplier: 1.11,
                armor_multiplier: 5.0,
                max_armor_reduction: 0.5,
                damage_multiplier: 1.0,
            },
            Class::Berserker => ClassConfiguration {
                health_multiplier: 4.0,
                weapon_multiplier: 2.0,
                weapon_gem_multiplier: 1,
                weapon_attribute_multiplier: 1,
                item_armor_multiplier: 15.0,
                main_attribute: AttributeType::Strength,
                item_bonus_multiplier: 1.1,
                armor_multiplier: 0.5,
                max_armor_reduction: 0.25,
                damage_multiplier: 1.25,
            },
            Class::DemonHunter => ClassConfiguration {
                health_multiplier: 4.0,
                weapon_multiplier: 2.5,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 2,
                item_armor_multiplier: 15.0,
                main_attribute: AttributeType::Dexterity,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 1.0,
                max_armor_reduction: 0.5,
                damage_multiplier: 1.0,
            },
            Class::Druid => ClassConfiguration {
                health_multiplier: 5.0,
                weapon_multiplier: 4.5,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 2,
                item_armor_multiplier: 7.5,
                main_attribute: AttributeType::Intelligence,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 1.0,
                max_armor_reduction: 0.25,
                damage_multiplier: 1.0 / 3.0,
            },
            Class::Bard => ClassConfiguration {
                health_multiplier: 2.0,
                weapon_multiplier: 4.5,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 2,
                item_armor_multiplier: 7.5,
                main_attribute: AttributeType::Intelligence,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 2.0,
                max_armor_reduction: 0.5,
                damage_multiplier: 1.125,
            },
            Class::Necromancer => ClassConfiguration {
                health_multiplier: 4.0,
                item_armor_multiplier: 3.0,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 2.0,
                weapon_multiplier: 4.5,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 2,
                main_attribute: AttributeType::Intelligence,
                damage_multiplier: 5.0 / 9.0,
                max_armor_reduction: 0.2,
            },
            Class::Paladin => ClassConfiguration {
                health_multiplier: 6.0,
                weapon_multiplier: 2.0,
                item_armor_multiplier: 15.0,
                item_bonus_multiplier: 1.0,
                armor_multiplier: 1.0,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 1,
                main_attribute: AttributeType::Strength,
                max_armor_reduction: 0.45,
                damage_multiplier: 0.833,
            },
            Class::PlagueDoctor => ClassConfiguration {
                health_multiplier: 4.0,
                weapon_multiplier: 2.0,
                item_armor_multiplier: 3.0,
                armor_multiplier: 2.0,
                weapon_gem_multiplier: 2,
                weapon_attribute_multiplier: 1,
                main_attribute: AttributeType::Dexterity,
                item_bonus_multiplier: 1.11,
                max_armor_reduction: 0.20,
                damage_multiplier: 1.25,
            },
        }
    }
}
